steps:
# For more information on what versions of Xcode are available see the following:
# https://github.com/microsoft/virtual-environments/blob/master/images/macos/macos-10.15-Readme.md
- script: build/scripts/xcode-update.sh
  displayName: Force Xcode Update
  env:
    XcodeOverride: $(XcodeOverride)
  condition: ne(variables['XcodeOverride'], '')

- task: UseDotNet@2
  displayName: 'Use global.json SDK'
  inputs:
    packageType: 'sdk'
    useGlobalJson: true

- script: |
    dotnet tool install --global boots
    boots --stable Mono
    boots --stable XamarinAndroid
    boots --stable XamariniOS
  displayName: Ensure Latest Xamarin & Mono SDKs