//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspector.Resources.Labels {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Inspector.Resources.Labels.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ups, algo ha ocurrido. Favor validar tu cuenta o contacto con tu supervisor..
        /// </summary>
        internal static string AccountInvalid {
            get {
                return ResourceManager.GetString("AccountInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta cuenta no esta activa..
        /// </summary>
        internal static string AccountNotActivated {
            get {
                return ResourceManager.GetString("AccountNotActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string ActionCancel {
            get {
                return ResourceManager.GetString("ActionCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string ActionNo {
            get {
                return ResourceManager.GetString("ActionNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string ActionOk {
            get {
                return ResourceManager.GetString("ActionOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si.
        /// </summary>
        internal static string ActionYes {
            get {
                return ResourceManager.GetString("ActionYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifique que todas las propiedades están correctas..
        /// </summary>
        internal static string AllFieldsInvalid {
            get {
                return ResourceManager.GetString("AllFieldsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zona asignada no procesada. Por favor intentelo de nuevo mas tarde. Si el problema persiste, contacte su supervisor..
        /// </summary>
        internal static string AssignedZoneNotProcessed {
            get {
                return ResourceManager.GetString("AssignedZoneNotProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este campo es requerido..
        /// </summary>
        internal static string FieldRequired {
            get {
                return ResourceManager.GetString("FieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las instituciones no han cargado correctamente, intentelo de nuevo mas tarde..
        /// </summary>
        internal static string GroupNotLoaded {
            get {
                return ResourceManager.GetString("GroupNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No pudimos cargar las incidencias..
        /// </summary>
        internal static string IncidentNotLoaded {
            get {
                return ResourceManager.GetString("IncidentNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo no valido. .
        /// </summary>
        internal static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo incorrecto o incompleto..
        /// </summary>
        internal static string InvalidField {
            get {
                return ResourceManager.GetString("InvalidField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero de teléfono incorrecto o incompleto..
        /// </summary>
        internal static string InvalidPhoneNumber {
            get {
                return ResourceManager.GetString("InvalidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No pudimos actualizar la lista..
        /// </summary>
        internal static string ListNotUpdated {
            get {
                return ResourceManager.GetString("ListNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máximo o mínimo de caracteres incorrectos..
        /// </summary>
        internal static string MaxMinInvalidField {
            get {
                return ResourceManager.GetString("MaxMinInvalidField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mínimo de caracteres es 10..
        /// </summary>
        internal static string MinLengthField10 {
            get {
                return ResourceManager.GetString("MinLengthField10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mínimo de caracteres es 12..
        /// </summary>
        internal static string MinLengthField12 {
            get {
                return ResourceManager.GetString("MinLengthField12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mínimo de caracteres es 6..
        /// </summary>
        internal static string MinLengthField6 {
            get {
                return ResourceManager.GetString("MinLengthField6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Seguro que deseas cerrar sesión?.
        /// </summary>
        internal static string RequetLogout {
            get {
                return ResourceManager.GetString("RequetLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No puedes digitar tu propia cédula..
        /// </summary>
        internal static string SameId {
            get {
                return ResourceManager.GetString("SameId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algo ha pasado. Intentelo de nuevo mas tarde..
        /// </summary>
        internal static string SomethingHappen {
            get {
                return ResourceManager.GetString("SomethingHappen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El ticket ha sido creado exitosamente..
        /// </summary>
        internal static string TicketCreated {
            get {
                return ResourceManager.GetString("TicketCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El ticket no ha sido creado, intentelo de nuevo mas tarde..
        /// </summary>
        internal static string TicketNotCreated {
            get {
                return ResourceManager.GetString("TicketNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El ticket ha sido actualizado exitosamente..
        /// </summary>
        internal static string TicketUpdated {
            get {
                return ResourceManager.GetString("TicketUpdated", resourceCulture);
            }
        }
    }
}
