name: Build Xamarin.Android app

on: [push]

jobs:
  build:

    runs-on: macos-latest
    env: 
      MONO_VERSION: '6.10'
      ANDROID_VERSION: '11.1'
      SLN_FILE_PATH: './src/Inspector.sln'
      CSPROJ_FILE_PATH: './src/Inspector.Android/Inspector.Android.csproj'
      BUILD_CONFIGURATION: Debug-Agent

    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        token: ${{ secrets.OGTIC_PAT }}

    - name: Set default Xamarin SDK versions
      run: |
        $VM_ASSETS/select-xamarin-sdk-v2.sh --mono=${{ env.MONO_VERSION }} --android=${{ env.ANDROID_VERSION }}

    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'

    - name: NuGet restore and Build
      run: |
        nuget restore ${{ env.SLN_FILE_PATH }}
        msbuild /t:PackageForAndroid /p:Configuration=${{ env.BUILD_CONFIGURATION }} /p:UseSharedCompilation=false ${{ env.CSPROJ_FILE_PATH }}
