name: Build Xamarin.Android app

on: [push]

jobs:
  build:

    runs-on: windows-latest
    env: 
      # Path to the solution file relative to the root of the project.
      SLN_FILE_PATH: 'PartsUnlimited-aspnet45'
      CSPROJ_FILE_PATH: './src/Inspector.Android/Inspector.Android.csproj'
      SOLUTION: 'PartsUnlimited-aspnet45/PartsUnlimited.sln'
      BUILD_PLATFORM: 'anycpu'
      BUILD_CONFIGURATION: Debug-Agent

    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        token: ${{ secrets.OGTIC_PAT }}

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      # Override language selection by uncommenting this and choosing your languages
      with:
        languages: csharp

    # - name: Set default Xamarin SDK versions
    #   run: |
    #     $VM_ASSETS/select-xamarin-sdk-v2.sh --mono=6.10 --android=11.1

    # - name: Setup .NET Core SDK 5.0.x
    #   uses: actions/setup-dotnet@v1
    #   with:
    #     dotnet-version: '5.0.x'

    - name: Add msbuild to PATH and build
      uses: microsoft/setup-msbuild@v1
    - run: |
        nuget restore ${{ env.SLN_FILE_PATH }}
        msbuild /t:PackageForAndroid /p:Configuration=${{ env.BUILD_CONFIGURATION }} /p:UseSharedCompilation=false ${{ env.CSPROJ_FILE_PATH }}

    # Initializes the CodeQL tools for scanning.
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
