name: Build Xamarin.Android app

on: [push]

jobs:
  build:

    runs-on: windows-latest
    env: 
      MONO_VERSION: '6.10'
      ANDROID_VERSION: '11.1'
      SLN_FILE_PATH: './src/Inspector.sln'
      CSPROJ_FILE_PATH: './src/Inspector.Android/Inspector.Android.csproj'
      BUILD_CONFIGURATION: Debug-Agent

    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        token: ${{ secrets.OGTIC_PAT }}

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: csharp
        config-file: ./.github/codeql/codeql-config.yml

    # - name: Set default Xamarin SDK versions
    #   run: |
    #     $VM_ASSETS/select-xamarin-sdk-v2.sh --mono=${{ env.MONO_VERSION }} --android=${{ env.ANDROID_VERSION }}

    - name: Add msbuild to PATH and build
      uses: microsoft/setup-msbuild@v1
    - run: |
        nuget restore ${{ env.SLN_FILE_PATH }}
        msbuild /t:PackageForAndroid /p:Configuration=${{ env.BUILD_CONFIGURATION }} /p:UseSharedCompilation=false ${{ env.CSPROJ_FILE_PATH }}

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
